### ISSUE TITLE
Filter recived messages

### ISSUE THREAD

**Issue by asghaier** [ahmed-sghaier/pynorcio#1]
Extract PRIVMSG: sender, receiver, message.

**Comment by AMhadhbi** [comment]
Bad Extract PRIVMSG sender, receiver, message

added to Ahmed Sghaier please complete the extract PRIMSG

**Comment by asghaier** [comment]
Sorry, I will not code for this issue. I have other tickets.
Please finish this issue. I will start coding for the other issue later supposing that the variables are correctly extracted.
I might help you with this issue if it is not solved by tomorrow night.

**Comment by asghaier** [comment]
Sender variable isn't filtered correctly, Message variable holds only the first word instead of the whole message.
Please fix that and clean up the code a little.
Thanks for the good work.

**Comment by AMhadhbi** [comment]
Sender variable is correctly done. Please check it.
About the Message variable, the console print only the first word because the space, so I will check it tomrrow.
Thanks for your help
Good Night

**Comment by asghaier** [comment]
Thank you for the great work :)
